apiVersion: skaffold/v4beta2
kind: Config
build:
  local:
    push: false
  artifacts:
    - image: arigatopix/multi-client
      context: client
      docker:
        dockerfile: Dockerfile.dev
      sync:
        manual:
          - src: 'src/**/*.js'
            dest: .
          - src: 'src/**/*.CSS'
            dest: .
          - src: 'src/**/*.html'
            dest: .
