apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: arigatopix-com-tls
spec:
  secretName: arigatopix-com
  issuerRef:
    name: letencrypt-prod
    kind: ClusterIssuer
  commonName: devx.pea.co.th
  dnsNames:
    - devx.pea.co.th
