apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: arigatopix-com-tls
spec:
  secertName: arigatopix-com
  issuerRef:
    name: letencrypt-prod
    kind: ClusterIssuer
  commonName: arigatopix.com
  dnsNames:
    - arigatopix.com
    - www.arigatopix.com
